version: 2.1

jobs:
  build_and_test:
    macos:
      # Use a valid CircleCI macOS image with Xcode installed
      xcode: "26.3.0"
    steps:
      - checkout
      - run:
          name: Debug repo root
          command: ls -la
      - run:
          name: Debug MPGitUserShowCase folder
          command: ls -la MPGitUserShowCase
      - run:
          name: Install Bundler
          command: gem install bundler -v 4.0.8
      - run:
          name: Install Dependencies
          command: cd MPGitUserShowCase && bundle install
      - run:
          name: Run Fastlane Simulator Tests
          command: cd MPGitUserShowCase/fastlane && bundle exec fastlane simulator_test

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - build_and_test

