version: 2.1

jobs:
  build_and_test:
    macos:
      # Use a valid CircleCI macOS image with Xcode installed
      xcode: "26.3.0"
    steps:
      - checkout
      - run:
          name: Debug repo root
          command: ls -la
      - run:
          name: Debug MPGitUserShowCase folder
          command: ls -la MPGitUserShowCase
      - run:
          name: Install Bundler
          command: gem install bundler -v 4.0.8
      - run:
          name: Install Dependencies
          command: cd MPGitUserShowCase && bundle install
      - run:
          name: Pre-boot simulator
          command: |
            xcrun simctl boot "iPhone 17 Pro" || true
            xcrun simctl bootstatus "iPhone 17 Pro" -b
      - run:
          name: Run Fastlane Simulator Tests
          command: cd MPGitUserShowCase/fastlane && bundle exec fastlane simulator_test
      - store_artifacts:
          path: MPGitUserShowCase/fastlane/test_output
          destination: test_output
      - store_test_results:
          path: MPGitUserShowCase/fastlane/test_output

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - build_and_test

